package Menu;

import figuras.Gandalf;
import figuras.Magito;
import figuras.TorreSauron;
import figuras.Triforce;

/**
 * Menú principal del proyecto
 * @author Kevin
 */
public class Menu extends javax.swing.JFrame
{

    /**
     * Creates new form Menu
     */
    public Menu()
    {
        initComponents();
        System.setProperty("sun.awt.noerasebackground", "true");
        
        Magito mg = new Magito();
        jDMago.add(mg);
        mg.setVisible(true);
        
        TorreSauron ts = new TorreSauron();
        jDTorreSauron.add(ts);
        ts.setVisible(true);
        
        Triforce tf = new Triforce();
        jDTriforce.add(tf);
        tf.setVisible(true);
        
        Gandalf gf = new Gandalf();
        jDGandalf.add(gf);
        gf.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        PMago = new javax.swing.JPanel();
        jDMago = new javax.swing.JDesktopPane();
        PTorreSauron = new javax.swing.JPanel();
        jDTorreSauron = new javax.swing.JDesktopPane();
        PTriforce = new javax.swing.JPanel();
        jDTriforce = new javax.swing.JDesktopPane();
        PGandalf = new javax.swing.JPanel();
        jDGandalf = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTabbedPane2MouseClicked(evt);
            }
        });

        PMago.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jDMagoLayout = new javax.swing.GroupLayout(jDMago);
        jDMago.setLayout(jDMagoLayout);
        jDMagoLayout.setHorizontalGroup(
            jDMagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jDMagoLayout.setVerticalGroup(
            jDMagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        PMago.add(jDMago, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Mago", PMago);

        PTorreSauron.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jDTorreSauronLayout = new javax.swing.GroupLayout(jDTorreSauron);
        jDTorreSauron.setLayout(jDTorreSauronLayout);
        jDTorreSauronLayout.setHorizontalGroup(
            jDTorreSauronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jDTorreSauronLayout.setVerticalGroup(
            jDTorreSauronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        PTorreSauron.add(jDTorreSauron, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Torre Sauron", PTorreSauron);

        PTriforce.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jDTriforceLayout = new javax.swing.GroupLayout(jDTriforce);
        jDTriforce.setLayout(jDTriforceLayout);
        jDTriforceLayout.setHorizontalGroup(
            jDTriforceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jDTriforceLayout.setVerticalGroup(
            jDTriforceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        PTriforce.add(jDTriforce, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Triforce", PTriforce);

        PGandalf.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jDGandalfLayout = new javax.swing.GroupLayout(jDGandalf);
        jDGandalf.setLayout(jDGandalfLayout);
        jDGandalfLayout.setHorizontalGroup(
            jDGandalfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jDGandalfLayout.setVerticalGroup(
            jDGandalfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        PGandalf.add(jDGandalf, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Gandalf", PGandalf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTabbedPane2MouseClicked
    {//GEN-HEADEREND:event_jTabbedPane2MouseClicked

    }//GEN-LAST:event_jTabbedPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PGandalf;
    private javax.swing.JPanel PMago;
    private javax.swing.JPanel PTorreSauron;
    private javax.swing.JPanel PTriforce;
    private javax.swing.JDesktopPane jDGandalf;
    private javax.swing.JDesktopPane jDMago;
    private javax.swing.JDesktopPane jDTorreSauron;
    private javax.swing.JDesktopPane jDTriforce;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
